name: Checks

on:
    #push:
    pull_request:
    #schedule:
    #    -   cron:  '0 3 * * *'

jobs:
    shellcheck: # https://github.com/marketplace/actions/shellcheck
        name: Shellcheck
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Run ShellCheck
                uses: ludeeus/action-shellcheck@master
                env:
                    SHELLCHECK_OPTS: -e SC1090
